[package]
name = "websocket1c"
version = "0.1.0"
edition = "2021"

[dependencies]
utf16_lit = "2.0"
native_api_1c = "0.10"
tokio = { version = "1.43", features = ["rt-multi-thread", "time"] }
tokio-tungstenite = "0.26"
futures-util = "0.3"

[lib] 
crate-type = ["cdylib"]