[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.remove-out.linux]
command = "rm"
args = ["-rf", "out"]

[tasks.remove-out.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
Remove-Item -LiteralPath "out" -Force -Recurse -ErrorAction SilentlyContinue
'''

[tasks.build-release-windows-32.windows]
command = "cargo"
args = ["build", "--release", "--target", "i686-pc-windows-msvc"]

[tasks.build-release-windows-64.windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-msvc"]

[tasks.build-release-linux-32.windows]
command = "cargo"
args = ["build", "--release", "--target", "i686-unknown-linux-gnu"]

[tasks.build-release-linux-64.windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-unknown-linux-gnu"]

[tasks.build-release-windows-32.linux]
command = "cargo"
args = ["build", "--release", "--target", "i686-pc-windows-gnu"]

[tasks.build-release-windows-64.linux]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-gnu"]

[tasks.build-release-linux-32.linux]
command = "cargo"
args = ["build", "--release", "--target", "i686-unknown-linux-gnu"]

[tasks.build-release-linux-64.linux]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-unknown-linux-gnu"]

[tasks.release]
run_task = { name = [
    "build-release-windows-32",
    "build-release-windows-64",
    "build-release-linux-32",
    "build-release-linux-64",
], parallel = true }

[tasks.pack-to-zip.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
New-Item -ItemType Directory -Path out -Force -ErrorAction SilentlyContinue
cp target/i686-pc-windows-msvc/release/websocket1c.dll out/Websocket1CAddIn_x32.dll
cp target/x86_64-pc-windows-msvc/release/websocket1c.dll out/Websocket1CAddIn_x64.dll
cp target/i686-unknown-linux-gnu/release/libwebsocket1c.so out/Websocket1CAddIn_x32.so
cp target/x86_64-unknown-linux-gnu/release/libwebsocket1c.so out/Websocket1CAddIn_x64.so
cp Manifest.xml out/
Compress-Archive -DestinationPath out/Websocket1CAddIn.zip -Path out/Websocket1CAddIn_x64.dll, out/Websocket1CAddIn_x32.dll, out/Websocket1CAddIn_x32.so, out/Websocket1CAddIn_x64.so, out/Manifest.xml -Force
'''

[tasks.pack-to-zip.linux]
script = '''
mkdir -p out
cp target/i686-pc-windows-gnu/release/websocket1c.dll out/Websocket1CAddIn_x32.dll
cp target/x86_64-pc-windows-gnu/release/websocket1c.dll out/Websocket1CAddIn_x64.dll
cp target/i686-unknown-linux-gnu/release/libwebsocket1c.so out/Websocket1CAddIn_x32.so
cp target/x86_64-unknown-linux-gnu/release/libwebsocket1c.so out/Websocket1CAddIn_x64.so
cp Manifest.xml out/
zip -r -j out/Websocket1CAddIn.zip out/Websocket1CAddIn_x64.dll, out/Websocket1CAddIn_x32.dll, out/Websocket1CAddIn_x32.so, out/Websocket1CAddIn_x64.so, out/Manifest.xml
'''

[tasks.pack]
dependencies = ["clean", "release", "remove-out", "pack-to-zip"]