[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "linker-flavor=ld.lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "linker-flavor=ld.lld"]

[target.i686-unknown-linux-musl]
rustflags = ["-C", "linker-flavor=ld.lld"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "linker-flavor=ld.lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "linker-flavor=ld.lld"]